// Shared constants used across multiple form step components

export const THAILAND_PROVINCES: string[] = [
  "กรุงเทพมหานคร",
  "กระบี่",
  "กาญจนบุรี",
  "กาฬสินธุ์",
  "กำแพงเพชร",
  "ขอนแก่น",
  "จันทบุรี",
  "ฉะเชิงเทรา",
  "ชลบุรี",
  "ชัยนาท",
  "ชัยภูมิ",
  "ชุมพร",
  "เชียงราย",
  "เชียงใหม่",
  "ตรัง",
  "ตราด",
  "ตาก",
  "นครนายก",
  "นครปฐม",
  "นครพนม",
  "นครราชสีมา",
  "นครศรีธรรมราช",
  "นครสวรรค์",
  "นนทบุรี",
  "นราธิวาส",
  "น่าน",
  "บึงกาฬ",
  "บุรีรัมย์",
  "ปทุมธานี",
  "ประจวบคีรีขันธ์",
  "ปราจีนบุรี",
  "ปัตตานี",
  "พระนครศรีอยุธยา",
  "พะเยา",
  "พังงา",
  "พัทลุง",
  "พิจิตร",
  "พิษณุโลก",
  "เพชรบุรี",
  "เพชรบูรณ์",
  "แพร่",
  "ภูเก็ต",
  "มหาสารคาม",
  "มุกดาหาร",
  "แม่ฮ่องสอน",
  "ยะลา",
  "ยโสธร",
  "ระนอง",
  "ระยอง",
  "ราชบุรี",
  "ลพบุรี",
  "ลำปาง",
  "ลำพูน",
  "เลย",
  "ศรีสะเกษ",
  "สกลนคร",
  "สงขลา",
  "สตูล",
  "สมุทรปราการ",
  "สมุทรสงคราม",
  "สมุทรสาคร",
  "สระแก้ว",
  "สระบุรี",
  "สิงห์บุรี",
  "สุโขทัย",
  "สุพรรณบุรี",
  "สุราษฎร์ธานี",
  "สุรินทร์",
  "หนองคาย",
  "หนองบัวลำภู",
  "อ่างทอง",
  "อำนาจเจริญ",
  "อุดรธานี",
  "อุตรดิตถ์",
  "อุทัยธานี",
  "อุบลราชธานี",
];

export const BANGKOK_DISTRICTS: string[] = [
  "พระนคร",
  "ดุสิต",
  "หนองจอก",
  "บางรัก",
  "บางเขน",
  "บางกะปิ",
  "ปทุมวัน",
  "ป้อมปราบศัตรูพ่าย",
  "พระโขนง",
  "มีนบุรี",
  "ลาดกระบัง",
  "ยานนาวา",
  "สัมพันธวงศ์",
  "พญาไท",
  "ธนบุรี",
  "บางกอกใหญ่",
  "ห้วยขวาง",
  "คลองสาน",
  "ตลิ่งชัน",
  "บางกอกน้อย",
  "บางขุนเทียน",
  "ภาษีเจริญ",
  "หนองแขม",
  "ราษฎร์บูรณะ",
  "บางพลัด",
  "ดินแดง",
  "บึงกุ่ม",
  "สาทร",
  "บางซื่อ",
  "จตุจักร",
  "บางคอแหลม",
  "ประเวศ",
  "คลองเตย",
  "สวนหลวง",
  "จอมทอง",
  "ดอนเมือง",
  "ราชเทวี",
  "ลาดพร้าว",
  "วัฒนา",
  "บางแค",
  "หลักสี่",
  "สายไหม",
  "คันนายาว",
  "สะพานสูง",
  "วังทองหลาง",
  "คลองสามวา",
  "บางนา",
  "ทวีวัฒนา",
  "ทุ่งครุ",
  "บางบอน",
];

export const ENGINEERING_PROGRAMS: string[] = [
  "หลักสูตรปริญญาตรี (ปกติ)",
  "สาขาวิชาวิศวกรรมโยธา",
  "สาขาวิชาวิศวกรรมไฟฟ้า",
  "สาขาวิชาวิศวกรรมเครื่องกล",
  "สาขาวิชาวิศวกรรมยานยนต์",
  "สาขาวิชาวิศวกรรมอุตสาหการ",
  "สาขาวิชาวิศวกรรมเคมี",
  "สาขาวิชาวิศวกรรมทรัพยากรธรณี",
  "สาขาวิชาวิศวกรรมปิโตรเลียม",
  "สาขาวิชาวิศวกรรมสิ่งแวดล้อม",
  "สาขาวิชาวิศวกรรมสำรวจ",
  "สาขาวิชาวิศวกรรมโลหการและวัสดุ",
  "สาขาวิชาวิศวกรรมคอมพิวเตอร์",
  "สาขาวิชาวิศวกรรมคอมพิวเตอร์และเทคโนโลยีดิจิทัล",
  "สาขาวิชาวิศวกรรมนิวเคลียร์และรังสี",
  "หลักสูตรปริญญาตรี (นานาชาติ)",
  "สาขาวิชาการออกแบบและการผลิตยานยนต์ (หลักสูตรนานาชาติ)",
  "สาขาวิชาวิศวกรรมนาโน (หลักสูตรนานาชาติ)",
  "สาขาวิชาวิศวกรรมสารสนเทศและการสื่อสาร (หลักสูตรนานาชาติ)",
  "สาขาวิชาวิศวกรรมอากาศยาน (หลักสูตรนานาชาติ)",
  "สาขาวิชาวิศวกรรมหุ่นยนต์และปัญญาประดิษฐ์ (หลักสูตรนานาชาติ)",
  "สาขาวิชาวิศวกรรมเคมีและกระบวนการ (หลักสูตรนานาชาติ)",
  "สาขาวิชาวิศวกรรมเซมิคอนดักเตอร์",
];

export const GENDER_OPTIONS = [
  { label: "ชาย", value: "male" },
  { label: "หญิง", value: "female" },
  { label: "ไม่ต้องการระบุ", value: "prefer_not_to_say" },
  { label: "อื่นๆ", value: "other" },
];

export const PARTICIPANT_TYPE_OPTIONS = [
  { label: "นักเรียน/ผู้ที่สนใจศึกษาต่อ", value: "student" },
  { label: "นิสิตปัจจุบันวิศวะจุฬาฯ", value: "intania" },
  { label: "นิสิตเก่าวิศวะจุฬาฯ", value: "alumni" },
  { label: "นิสิตจากคณะ/มหาลัยอื่น", value: "outside_student" },
  { label: "ครู", value: "teacher" },
  { label: "ผู้ปกครอง/บุคคลภายนอก", value: "other" },
];

export const TRANSPORT_MODE_OPTIONS = [
  { label: "รถยนต์ส่วนบุคคล", value: "personal_car" },
  { label: "เที่ยวบินในประเทศ", value: "domestic_flight" },
  { label: "รถกระบะส่วนบุคคล", value: "personal_pickup_truck" },
  { label: "รถตู้ประจำทาง", value: "public_van" },
  { label: "แท็กซี่", value: "taxi" },
  { label: "รถโดยสารประจำทาง", value: "public_bus" },
  { label: "รถยนต์ไฟฟ้าส่วนบุคคล", value: "personal_electric_car" },
  { label: "รถไฟดีเซลราง", value: "diesel_railcar" },
  { label: "รถตู้ส่วนบุคคล", value: "personal_van" },
  { label: "เรือสาธารณะ", value: "public_boat" },
  { label: "จักรยานยนต์", value: "motorcycle" },
  { label: "รถไฟฟ้า", value: "electric_train" },
];

export const ORIGIN_LOCATIONS = [
  { label: "พระนคร", value: "phra_nakhon" },
  { label: "ดุสิต", value: "dusit" },
  { label: "หนองจอก", value: "nong_chok" },
  { label: "บางรัก", value: "bang_rak" },
  { label: "บางเขน", value: "bang_khen" },
  { label: "บางกะปิ", value: "bang_kapi" },
  { label: "ปทุมวัน", value: "pathum_wan" },
  { label: "ป้อมปราบศัตรูพ่าย", value: "pom_prap_sattru_phai" },
  { label: "พระโขนง", value: "phra_khanong" },
  { label: "มีนบุรี", value: "min_buri" },
  { label: "ลาดกระบัง", value: "lat_krabang" },
  { label: "ยานนาวา", value: "yan_nawa" },
  { label: "คลองสาน", value: "khlong_san" },
  { label: "บางแค", value: "bang_khae" },
  { label: "บางคอแหลม", value: "bang_kho_laem" },
  { label: "บางซื่อ", value: "bang_sue" },
  { label: "บางนา", value: "bang_na" },
  { label: "ทวีวัฒนา", value: "thawi_watthana" },
  { label: "ทุ่งครุ", value: "thung_khru" },
  { label: "บางพลัด", value: "bang_plad" },
  { label: "บางบอน", value: "bang_bon" },
  { label: "บางขุนเทียน", value: "bang_khun_thian" },
  { label: "ภาษีเจริญ", value: "phasi_charoen" },
  { label: "ตลิ่งชัน", value: "taling_chan" },
  { label: "จตุจักร", value: "chatuchak" },
  { label: "หลักสี่", value: "lak_si" },
  { label: "สายไหม", value: "sai_mai" },
  { label: "คลองเตย", value: "khlong_toei" },
  { label: "สวนหลวง", value: "suan_luang" },
  { label: "ราษฎร์บูรณะ", value: "rat_burana" },
  { label: "ห้วยขวาง", value: "huai_khwang" },
  { label: "คลองสามวา", value: "khlong_sam_wa" },
  { label: "วังทองหลาง", value: "wang_thonglang" },
  { label: "สะพานสูง", value: "saphan_sung" },
  { label: "บางกอกใหญ่", value: "bangkok_yai" },
  { label: "บางกอกน้อย", value: "bangkok_noi" },
  { label: "สัมพันธวงศ์", value: "samphanthawong" },
  { label: "พญาไท", value: "phaya_thai" },
  { label: "ราชเทวี", value: "ratchathewi" },
  { label: "ดอนเมือง", value: "don_mueang" },
  { label: "ประเวศ", value: "prawet" },
  { label: "ดินแดง", value: "din_daeng" },
  { label: "บึงกุ่ม", value: "bueng_kum" },
  { label: "สาทร", value: "sathon" },
  { label: "จอมทอง", value: "chom_thong" },
  { label: "วัฒนา", value: "watthana" },
  { label: "คันนายาว", value: "kannayao" },
  { label: "อำนาจเจริญ", value: "amnat_charoen" },
  { label: "อ่างทอง", value: "ang_thong" },
  { label: "บึงกาฬ", value: "bueng_kan" },
  { label: "บุรีรัมย์", value: "buriram" },
  { label: "ฉะเชิงเทรา", value: "chachoengsao" },
  { label: "ชัยนาท", value: "chai_nat" },
  { label: "ชัยภูมิ", value: "chaiyaphum" },
  { label: "จันทบุรี", value: "chanthaburi" },
  { label: "เชียงใหม่", value: "chiang_mai" },
  { label: "เชียงราย", value: "chiang_rai" },
  { label: "ชลบุรี", value: "chonburi" },
  { label: "ชุมพร", value: "chumphon" },
  { label: "กาฬสินธุ์", value: "kalasin" },
  { label: "กำแพงเพชร", value: "kamphaeng_phet" },
  { label: "กาญจนบุรี", value: "kanchanaburi" },
  { label: "ขอนแก่น", value: "khon_kaen" },
  { label: "กระบี่", value: "krabi" },
  { label: "ลำปาง", value: "lampang" },
  { label: "ลำพูน", value: "lamphun" },
  { label: "เลย", value: "loei" },
  { label: "ลพบุรี", value: "lopburi" },
  { label: "แม่ฮ่องสอน", value: "mae_hong_son" },
  { label: "มหาสารคาม", value: "maha_sarakham" },
  { label: "มุกดาหาร", value: "mukdahan" },
  { label: "นครนายก", value: "nakhon_nayok" },
  { label: "นครปฐม", value: "nakhon_pathom" },
  { label: "นครพนม", value: "nakhon_phanom" },
  { label: "นครราชสีมา", value: "nakhon_ratchasima" },
  { label: "นครสวรรค์", value: "nakhon_sawan" },
  { label: "นครศรีธรรมราช", value: "nakhon_si_thammarat" },
  { label: "น่าน", value: "nan" },
  { label: "นราธิวาส", value: "narathiwat" },
  { label: "หนองบัวลำภู", value: "nong_bua_lamphu" },
  { label: "หนองคาย", value: "nong_khai" },
  { label: "นนทบุรี", value: "nonthaburi" },
  { label: "ปทุมธานี", value: "pathum_thani" },
  { label: "ปัตตานี", value: "pattani" },
  { label: "พังงา", value: "phang_nga" },
  { label: "พัทลุง", value: "phatthalung" },
  { label: "พะเยา", value: "phayao" },
  { label: "เพชรบูรณ์", value: "phetchabun" },
  { label: "เพชรบุรี", value: "phetchaburi" },
  { label: "พิจิตร", value: "phichit" },
  { label: "พิษณุโลก", value: "phitsanulok" },
  { label: "พระนครศรีอยุธยา", value: "phra_nakhon_si_ayutthaya" },
  { label: "แพร่", value: "phrae" },
  { label: "ภูเก็ต", value: "phuket" },
  { label: "ปราจีนบุรี", value: "prachinburi" },
  { label: "ประจวบคีรีขันธ์", value: "prachuap_khiri_khan" },
  { label: "ระนอง", value: "ranong" },
  { label: "ราชบุรี", value: "ratchaburi" },
  { label: "ระยอง", value: "rayong" },
  { label: "ร้อยเอ็ด", value: "roi_et" },
  { label: "สระแก้ว", value: "sa_kaeo" },
  { label: "สกลนคร", value: "sakon_nakhon" },
  { label: "สมุทรปราการ", value: "samut_prakan" },
  { label: "สมุทรสาคร", value: "samut_sakhon" },
  { label: "สมุทรสงคราม", value: "samut_songkhram" },
  { label: "สระบุรี", value: "sara_buri" },
  { label: "สตูล", value: "satun" },
  { label: "สิงห์บุรี", value: "sing_buri" },
  { label: "ศรีสะเกษ", value: "sisaket" },
  { label: "สงขลา", value: "songkhla" },
  { label: "สุโขทัย", value: "sukhothai" },
  { label: "สุพรรณบุรี", value: "suphan_buri" },
  { label: "สุราษฎร์ธานี", value: "surat_thani" },
  { label: "สุรินทร์", value: "surin" },
  { label: "ตาก", value: "tak" },
  { label: "ตรัง", value: "trang" },
  { label: "ตราด", value: "trat" },
  { label: "อุบลราชธานี", value: "ubon_ratchathani" },
  { label: "อุดรธานี", value: "udon_thani" },
  { label: "อุทัยธานี", value: "uthai_thani" },
  { label: "อุตรดิตถ์", value: "uttaradit" },
  { label: "ยะลา", value: "yala" },
  { label: "ยโสธร", value: "yasothon" },
];
