// Shared constants used across multiple form step components

export const THAILAND_PROVINCES: string[] = [
  "กรุงเทพมหานคร",
  "กระบี่",
  "กาญจนบุรี",
  "กาฬสินธุ์",
  "กำแพงเพชร",
  "ขอนแก่น",
  "จันทบุรี",
  "ฉะเชิงเทรา",
  "ชลบุรี",
  "ชัยนาท",
  "ชัยภูมิ",
  "ชุมพร",
  "เชียงราย",
  "เชียงใหม่",
  "ตรัง",
  "ตราด",
  "ตาก",
  "นครนายก",
  "นครปฐม",
  "นครพนม",
  "นครราชสีมา",
  "นครศรีธรรมราช",
  "นครสวรรค์",
  "นนทบุรี",
  "นราธิวาส",
  "น่าน",
  "บึงกาฬ",
  "บุรีรัมย์",
  "ปทุมธานี",
  "ประจวบคีรีขันธ์",
  "ปราจีนบุรี",
  "ปัตตานี",
  "พระนครศรีอยุธยา",
  "พะเยา",
  "พังงา",
  "พัทลุง",
  "พิจิตร",
  "พิษณุโลก",
  "เพชรบุรี",
  "เพชรบูรณ์",
  "แพร่",
  "ภูเก็ต",
  "มหาสารคาม",
  "มุกดาหาร",
  "แม่ฮ่องสอน",
  "ยะลา",
  "ยโสธร",
  "ระนอง",
  "ระยอง",
  "ราชบุรี",
  "ลพบุรี",
  "ลำปาง",
  "ลำพูน",
  "เลย",
  "ศรีสะเกษ",
  "สกลนคร",
  "สงขลา",
  "สตูล",
  "สมุทรปราการ",
  "สมุทรสงคราม",
  "สมุทรสาคร",
  "สระแก้ว",
  "สระบุรี",
  "สิงห์บุรี",
  "สุโขทัย",
  "สุพรรณบุรี",
  "สุราษฎร์ธานี",
  "สุรินทร์",
  "หนองคาย",
  "หนองบัวลำภู",
  "อ่างทอง",
  "อำนาจเจริญ",
  "อุดรธานี",
  "อุตรดิตถ์",
  "อุทัยธานี",
  "อุบลราชธานี",
];

export const BANGKOK_DISTRICTS: string[] = [
  "พระนคร",
  "ดุสิต",
  "หนองจอก",
  "บางรัก",
  "บางเขน",
  "บางกะปิ",
  "ปทุมวัน",
  "ป้อมปราบศัตรูพ่าย",
  "พระโขนง",
  "มีนบุรี",
  "ลาดกระบัง",
  "ยานนาวา",
  "สัมพันธวงศ์",
  "พญาไท",
  "ธนบุรี",
  "บางกอกใหญ่",
  "ห้วยขวาง",
  "คลองสาน",
  "ตลิ่งชัน",
  "บางกอกน้อย",
  "บางขุนเทียน",
  "ภาษีเจริญ",
  "หนองแขม",
  "ราษฎร์บูรณะ",
  "บางพลัด",
  "ดินแดง",
  "บึงกุ่ม",
  "สาทร",
  "บางซื่อ",
  "จตุจักร",
  "บางคอแหลม",
  "ประเวศ",
  "คลองเตย",
  "สวนหลวง",
  "จอมทอง",
  "ดอนเมือง",
  "ราชเทวี",
  "ลาดพร้าว",
  "วัฒนา",
  "บางแค",
  "หลักสี่",
  "สายไหม",
  "คันนายาว",
  "สะพานสูง",
  "วังทองหลาง",
  "คลองสามวา",
  "บางนา",
  "ทวีวัฒนา",
  "ทุ่งครุ",
  "บางบอน",
];

export const ENGINEERING_PROGRAMS: string[] = [
  "หลักสูตรปริญญาตรี (ปกติ)",
  "สาขาวิชาวิศวกรรมโยธา",
  "สาขาวิชาวิศวกรรมไฟฟ้า",
  "สาขาวิชาวิศวกรรมเครื่องกล",
  "สาขาวิชาวิศวกรรมยานยนต์",
  "สาขาวิชาวิศวกรรมอุตสาหการ",
  "สาขาวิชาวิศวกรรมเคมี",
  "สาขาวิชาวิศวกรรมทรัพยากรธรณี",
  "สาขาวิชาวิศวกรรมปิโตรเลียม",
  "สาขาวิชาวิศวกรรมสิ่งแวดล้อม",
  "สาขาวิชาวิศวกรรมสำรวจ",
  "สาขาวิชาวิศวกรรมโลหการและวัสดุ",
  "สาขาวิชาวิศวกรรมคอมพิวเตอร์",
  "สาขาวิชาวิศวกรรมคอมพิวเตอร์และเทคโนโลยีดิจิทัล",
  "สาขาวิชาวิศวกรรมนิวเคลียร์และรังสี",
  "หลักสูตรปริญญาตรี (นานาชาติ)",
  "สาขาวิชาการออกแบบและการผลิตยานยนต์ (หลักสูตรนานาชาติ)",
  "สาขาวิชาวิศวกรรมนาโน (หลักสูตรนานาชาติ)",
  "สาขาวิชาวิศวกรรมสารสนเทศและการสื่อสาร (หลักสูตรนานาชาติ)",
  "สาขาวิชาวิศวกรรมอากาศยาน (หลักสูตรนานาชาติ)",
  "สาขาวิชาวิศวกรรมหุ่นยนต์และปัญญาประดิษฐ์ (หลักสูตรนานาชาติ)",
  "สาขาวิชาวิศวกรรมเคมีและกระบวนการ (หลักสูตรนานาชาติ)",
  "สาขาวิชาวิศวกรรมเซมิคอนดักเตอร์",
];

export const GENDER_OPTIONS = [
  { label: "ชาย", value: "male" },
  { label: "หญิง", value: "female" },
  { label: "ไม่ต้องการระบุ", value: "prefer_not_to_say" },
  { label: "อื่นๆ", value: "other" },
];

export const PARTICIPANT_TYPE_OPTIONS = [
  { label: "นักเรียน/ผู้ที่สนใจศึกษาต่อ", value: "student" },
  { label: "นิสิตปัจจุบัน/นิสิตเก่าวิศวะจุฬาฯ", value: "intania" },
  { label: "นิสิต/นักศึกษาจากมหาลัยอื่น", value: "other_university_student" },
  { label: "ครู", value: "teacher" },
  { label: "ผู้ปกครอง/บุคคลภายนอก", value: "other" },
];

export const TRANSPORT_MODE_OPTIONS = [
  { label: "รถยนต์ส่วนบุคคล", value: "personal_car" },
  { label: "เที่ยวบินในประเทศ", value: "domestic_flight" },
  { label: "รถกระบะส่วนบุคคล", value: "personal_pickup_truck" },
  { label: "รถตู้ประจำทาง", value: "public_van" },
  { label: "แท็กซี่", value: "taxi" },
  { label: "รถโดยสารประจำทาง", value: "public_bus" },
  { label: "รถยนต์ไฟฟ้าส่วนบุคคล", value: "personal_electric_car" },
  { label: "รถไฟดีเซลราง", value: "diesel_railcar" },
  { label: "รถตู้ส่วนบุคคล", value: "personal_van" },
  { label: "เรือสาธารณะ", value: "public_boat" },
  { label: "จักรยานยนต์", value: "motorcycle" },
  { label: "รถไฟฟ้า", value: "electric_train" },
];

export const ORIGIN_LOCATIONS = [
  { label: "เขตพระนคร", value: "phra_nakhon" },
  { label: "เขตดุสิต", value: "dusit" },
  { label: "เขตหนองจอก", value: "nong_chok" },
  { label: "เขตบางรัก", value: "bang_rak" },
  { label: "เขตบางเขน", value: "bang_khen" },
  { label: "เขตบางกะปิ", value: "bang_kapi" },
  { label: "เขตปทุมวัน", value: "pathum_wan" },
  { label: "เขตป้อมปราบศัตรูพ่าย", value: "pom_prap_sattru_phai" },
  { label: "เขตพระโขนง", value: "phra_khanong" },
  { label: "เขตมีนบุรี", value: "min_buri" },
  { label: "เขตลาดกระบัง", value: "lat_krabang" },
  { label: "เขตยานนาวา", value: "yan_nawa" },
  { label: "เขตคลองสาน", value: "khlong_san" },
  { label: "เขตบางแค", value: "bang_khae" },
  { label: "เขตบางคอแหลม", value: "bang_kho_laem" },
  { label: "เขตบางซื่อ", value: "bang_sue" },
  { label: "เขตบางนา", value: "bang_na" },
  { label: "เขตทวีวัฒนา", value: "thawi_watthana" },
  { label: "เขตทุ่งครุ", value: "thung_khru" },
  { label: "เขตบางพลัด", value: "bang_plad" },
  { label: "เขตบางบอน", value: "bang_bon" },
  { label: "เขตบางขุนเทียน", value: "bang_khun_thian" },
  { label: "เขตภาษีเจริญ", value: "phasi_charoen" },
  { label: "เขตตลิ่งชัน", value: "taling_chan" },
  { label: "เขตจตุจักร", value: "chatuchak" },
  { label: "เขตหลักสี่", value: "lak_si" },
  { label: "เขตสายไหม", value: "sai_mai" },
  { label: "เขตคลองเตย", value: "khlong_toei" },
  { label: "เขตสวนหลวง", value: "suan_luang" },
  { label: "เขตราษฎร์บูรณะ", value: "rat_burana" },
  { label: "เขตห้วยขวาง", value: "huai_khwang" },
  { label: "เขตคลองสามวา", value: "khlong_sam_wa" },
  { label: "เขตวังทองหลาง", value: "wang_thonglang" },
  { label: "เขตสะพานสูง", value: "saphan_sung" },
  { label: "เขตบางกอกใหญ่", value: "bangkok_yai" },
  { label: "เขตบางกอกน้อย", value: "bangkok_noi" },
  { label: "เขตสัมพันธวงศ์", value: "samphanthawong" },
  { label: "เขตพญาไท", value: "phaya_thai" },
  { label: "เขตราชเทวี", value: "ratchathewi" },
  { label: "เขตดอนเมือง", value: "don_mueang" },
  { label: "เขตประเวศ", value: "prawet" },
  { label: "เขตดินแดง", value: "din_daeng" },
  { label: "เขตบึงกุ่ม", value: "bueng_kum" },
  { label: "เขตสาทร", value: "sathon" },
  { label: "เขตจอมทอง", value: "chom_thong" },
  { label: "เขตวัฒนา", value: "watthana" },
  { label: "เขตคันนายาว", value: "kannayao" },
  { label: "จังหวัดอำนาจเจริญ", value: "amnat_charoen" },
  { label: "จังหวัดอ่างทอง", value: "ang_thong" },
  { label: "จังหวัดบึงกาฬ", value: "bueng_kan" },
  { label: "จังหวัดบุรีรัมย์", value: "buriram" },
  { label: "จังหวัดฉะเชิงเทรา", value: "chachoengsao" },
  { label: "จังหวัดชัยนาท", value: "chai_nat" },
  { label: "จังหวัดชัยภูมิ", value: "chaiyaphum" },
  { label: "จังหวัดจันทบุรี", value: "chanthaburi" },
  { label: "จังหวัดเชียงใหม่", value: "chiang_mai" },
  { label: "จังหวัดเชียงราย", value: "chiang_rai" },
  { label: "จังหวัดชลบุรี", value: "chonburi" },
  { label: "จังหวัดชุมพร", value: "chumphon" },
  { label: "จังหวัดกาฬสินธุ์", value: "kalasin" },
  { label: "จังหวัดกำแพงเพชร", value: "kamphaeng_phet" },
  { label: "จังหวัดกาญจนบุรี", value: "kanchanaburi" },
  { label: "จังหวัดขอนแก่น", value: "khon_kaen" },
  { label: "จังหวัดกระบี่", value: "krabi" },
  { label: "จังหวัดลำปาง", value: "lampang" },
  { label: "จังหวัดลำพูน", value: "lamphun" },
  { label: "จังหวัดเลย", value: "loei" },
  { label: "จังหวัดลพบุรี", value: "lopburi" },
  { label: "จังหวัดแม่ฮ่องสอน", value: "mae_hong_son" },
  { label: "จังหวัดมหาสารคาม", value: "maha_sarakham" },
  { label: "จังหวัดมุกดาหาร", value: "mukdahan" },
  { label: "จังหวัดนครนายก", value: "nakhon_nayok" },
  { label: "จังหวัดนครปฐม", value: "nakhon_pathom" },
  { label: "จังหวัดนครพนม", value: "nakhon_phanom" },
  { label: "จังหวัดนครราชสีมา", value: "nakhon_ratchasima" },
  { label: "จังหวัดนครสวรรค์", value: "nakhon_sawan" },
  { label: "จังหวัดนครศรีธรรมราช", value: "nakhon_si_thammarat" },
  { label: "จังหวัดน่าน", value: "nan" },
  { label: "จังหวัดนราธิวาส", value: "narathiwat" },
  { label: "จังหวัดหนองบัวลำภู", value: "nong_bua_lamphu" },
  { label: "จังหวัดหนองคาย", value: "nong_khai" },
  { label: "จังหวัดนนทบุรี", value: "nonthaburi" },
  { label: "จังหวัดปทุมธานี", value: "pathum_thani" },
  { label: "จังหวัดปัตตานี", value: "pattani" },
  { label: "จังหวัดพังงา", value: "phang_nga" },
  { label: "จังหวัดพัทลุง", value: "phatthalung" },
  { label: "จังหวัดพะเยา", value: "phayao" },
  { label: "จังหวัดเพชรบูรณ์", value: "phetchabun" },
  { label: "จังหวัดเพชรบุรี", value: "phetchaburi" },
  { label: "จังหวัดพิจิตร", value: "phichit" },
  { label: "จังหวัดพิษณุโลก", value: "phitsanulok" },
  { label: "จังหวัดพระนครศรีอยุธยา", value: "phra_nakhon_si_ayutthaya" },
  { label: "จังหวัดแพร่", value: "phrae" },
  { label: "จังหวัดภูเก็ต", value: "phuket" },
  { label: "จังหวัดปราจีนบุรี", value: "prachinburi" },
  { label: "จังหวัดประจวบคีรีขันธ์", value: "prachuap_khiri_khan" },
  { label: "จังหวัดระนอง", value: "ranong" },
  { label: "จังหวัดราชบุรี", value: "ratchaburi" },
  { label: "จังหวัดระยอง", value: "rayong" },
  { label: "จังหวัดร้อยเอ็ด", value: "roi_et" },
  { label: "จังหวัดสระแก้ว", value: "sa_kaeo" },
  { label: "จังหวัดสกลนคร", value: "sakon_nakhon" },
  { label: "จังหวัดสมุทรปราการ", value: "samut_prakan" },
  { label: "จังหวัดสมุทรสาคร", value: "samut_sakhon" },
  { label: "จังหวัดสมุทรสงคราม", value: "samut_songkhram" },
  { label: "จังหวัดสระบุรี", value: "sara_buri" },
  { label: "จังหวัดสตูล", value: "satun" },
  { label: "จังหวัดสิงห์บุรี", value: "sing_buri" },
  { label: "จังหวัดศรีสะเกษ", value: "sisaket" },
  { label: "จังหวัดสงขลา", value: "songkhla" },
  { label: "จังหวัดสุโขทัย", value: "sukhothai" },
  { label: "จังหวัดสุพรรณบุรี", value: "suphan_buri" },
  { label: "จังหวัดสุราษฎร์ธานี", value: "surat_thani" },
  { label: "จังหวัดสุรินทร์", value: "surin" },
  { label: "จังหวัดตาก", value: "tak" },
  { label: "จังหวัดตรัง", value: "trang" },
  { label: "จังหวัดตราด", value: "trat" },
  { label: "จังหวัดอุบลราชธานี", value: "ubon_ratchathani" },
  { label: "จังหวัดอุดรธานี", value: "udon_thani" },
  { label: "จังหวัดอุทัยธานี", value: "uthai_thani" },
  { label: "จังหวัดอุตรดิตถ์", value: "uttaradit" },
  { label: "จังหวัดยะลา", value: "yala" },
  { label: "จังหวัดยโสธร", value: "yasothon" },
];
